### ISSUE TITLE
proper format for full spectra

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmr-dataset1#1]
It seems that the Bruker jcamp files created by default are not readable by drag and drop. Only the fid's can be imported so far

**Comment by lpatiny** [comment]
The jcamp for the 1D contains at the same time the FID and the FT file and this is currently problematics and I don't know exactly how we will deal with those jcamp that containing many spectra (need to find a solution for this but it is more graphically problem).

Because we also have the FID it would be better is you export a jcamp with only 'real+imaginary'.

**Comment by nes-cgn** [comment]
@lpatiny , for the nmr-dataset1, it seems that I do not have the right to upload files. Which would be really helpful. I would replace all the 1D files which do not work properly (1H, 13C, DEPT135 etc.) for the three examples and could then start to add some more. I checked all the export options from TopSpin and tested all the (16) options that make sense. Could you grant me access?
